name: Website Screenshot
on:
  schedule: [{cron: "0 */12 * * *"}]   # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics Screenshot
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Ace Interview
          plugin_screenshot_url: https://ace-interview-2kxa.vercel.app/
          plugin_screenshot_selector: body
